services:
  db:
    image: postgres
    container_name: test-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: ihavegpuremake
      POSTGRES_PASSWORD: 12345678
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#    restart: always