server:
  shutdown: graceful
  port: 8080
spring:
  application:
    name: ihaveGPU
  profiles:
    active: "local"
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    drop-first: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      default_schema: public
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
        format_sql: true
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

logging:
  level:
    org:
      hibernate:
        #        sql: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework:
        web:
          servlet:
            handler:
              HandlerMappingIntrospector: ERROR
    root: INFO
    org.springframework.web: INFO
springdoc:
  api-docs:
    path: /api-docs
  enable-native-support: true
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    path: /swagger-ui
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ihaveGPUremake?searchpath=public&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok&prepareThreshold=0
    username: root
    password: 12345678
    hikari:
      schema: public
      connectionTimeout: 30000
      leakDetectionThreshold: 120000
  data:
    redis:
      repositories:
        enabled: true
      host: localhost
      port: 6379
      database: 0
      timeout: 60000
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://your-dev-database-host:5432/ihaveGPUremake?searchpath=public&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok
    username: your-dev-username
    password: your-dev-password
    hikari:
      schema: public
      connectionTimeout: 30000
      leakDetectionThreshold: 120000
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://your-prod-database-host:5432/ihaveGPUremake?searchpath=public&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok
    username: your-prod-username
    password: your-prod-password
    hikari:
      schema: public
      connectionTimeout: 30000
      leakDetectionThreshold: 120000

